name: deploy-api-docs
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
     uses: vapor/api-docs/.github/workflows/build-and-deploy-docs-workflow.yml
     with:
       package_name: vapor
       modules: Vapor,XCTVapor
