name: Generate Sponsors README
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSORS_PAT }}
          file: "README.md"
          minimum: 500
          maximum: 9900
          marker: "backers"
          organization: true

      # Here we can eventually add sponsors too rather than just backers

      - name: Get token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.PENNY_APP_ID }}
          private_key: ${{ secrets.PENNY_APP_PRIVATE_KEY }}
          repository: vapor/vapor

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v5
        with: 
          commit-message: Update README with new sponsor
          committer: "Penny[bot] <360798+penny[bot]@vapor.codes>"
          author: "Penny[bot] <360798+penny[bot]@vapor.codes>"
          branch: new-sponsor
          delete-branch: true
          title: Update README with new Sponsor
          body: Update README adding new sponsor
          labels: no-release-needed
      
      # We can comment this out if we want to automate approve and merge
      
      # - name: Enable Pull Request Automerge
      #   if: steps.cpr.outputs.pull-request-operation == 'created'
      #   uses: peter-evans/enable-pull-request-automerge@v2
      #   with:
      #     token: ${{ secrets.SPONSORS_PR_PAT }}
      #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      #     merge-method: merge

      # - name: Auto approve
      #   if: steps.cpr.outputs.pull-request-operation == 'created'
      #   uses: juliangruber/approve-pull-request-action@v2
      #   with:
      #     github-token: ${{ secrets.SPONSORS_PR_PAT }}
      #     number: ${{ steps.cpr.outputs.pull-request-number }}
